# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
server:
  port: ${PORT:80}
spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
  datasource:
    url: ${DB_CONNECTION_URL:jdbc:sqlserver://localhost:1433;databaseName=Movie;encrypt=true;trustServerCertificate=true}
    username: ${DB_CONNECTION_USERNAME:sa}
    password: ${DB_CONNECTION_PASSWORD:123456789}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  application:
    name: movie
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jpa:
    hibernate:
      ddl-auto: validate
      enable: false
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
          dialect: org.hibernate.dialect.SQLServerDialect
file:
  upload-dir: ${UPLOAD_DIR:File}
app:
  jwt:
    secret-key: '"phuong"'
    duration: 604800000
springdoc:
  override-with-generic-response: false
